# Generated by Django 4.1.6 on 2023-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=32, null=True)),
                ('callback', models.CharField(max_length=64, null=True)),
                ('message_text', models.TextField()),
                ('keyboard', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'telegram_bot_command',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=7)),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram_bot_log',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=32)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram_bot_user',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('private', models.BooleanField(default=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_stopped', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(related_name='allowed_users', to='telegram_bot.telegrambotuser')),
                ('commands', models.ManyToManyField(related_name='commands', to='telegram_bot.telegrambotcommand')),
                ('logs', models.ManyToManyField(related_name='telegram_bot_logs', to='telegram_bot.telegrambotlog')),
                ('users', models.ManyToManyField(related_name='users', to='telegram_bot.telegrambotuser')),
            ],
            options={
                'db_table': 'telegram_bot',
            },
        ),
    ]
