# Generated by Django 4.2.1 on 2023-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_remove_telegrambotuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotcommandkeyboardbutton',
            name='url',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
