# Generated by Django 4.2.1 on 2023-06-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_telegrambot_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='name',
            new_name='username',
        ),
    ]
