# Generated by Django 4.2.1 on 2023-06-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_alter_telegrambot_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/commands/'),
        ),
    ]
