# Generated by Django 4.2.1 on 2023-07-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_telegrambotcommand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotcommand',
            name='database_record',
            field=models.JSONField(blank=True, null=True, verbose_name='Запись в базу данных'),
        ),
    ]
