# Generated by Django 4.2.5 on 2023-10-20 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0019_alter_telegrambot_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='@username'),
        ),
    ]
