# Generated by Django 4.2.5 on 2023-10-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0021_remove_telegrambotcommandmessagetext_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='telegram_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='telegram_bot.telegrambot', verbose_name='Telegram бот'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommandkeyboard',
            name='telegram_bot_command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='telegram_bot.telegrambotcommand'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommandkeyboardbutton',
            name='telegram_bot_command_keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='telegram_bot.telegrambotcommandkeyboard'),
        ),
        migrations.AlterField(
            model_name='telegrambotuser',
            name='telegram_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='telegram_bot.telegrambot', verbose_name='Telegram бот'),
        ),
    ]
