# Generated by Django 5.0.4 on 2024-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='Фамилия')),
                ('_confirm_code', models.CharField(db_column='confirm_code', max_length=25, null=True, verbose_name='Код подтверждения')),
                ('confirm_code_generation_date', models.DateTimeField(null=True, verbose_name='Код подтверждения сгенерирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
    ]
