# Initially generated by Django 5.0.6 on 2025-12-09 07:07

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils import timezone

from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..models import User
else:
    User = Any


def set_accepted_terms_for_existing_users(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    user_model: type[User] = apps.get_model('users', 'User')

    update_users: list[User] = []
    current_date: datetime = timezone.now()

    for user in user_model.objects.iterator():
        user.accepted_terms = True
        user.terms_accepted_date = current_date
        update_users.append(user)

    user_model.objects.bulk_update(
        update_users, fields=['accepted_terms', 'terms_accepted_date']
    )


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]
    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(
                default=False, verbose_name='Принятие условий сервиса'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дата принятия условий сервиса'
            ),
        ),
        migrations.RunPython(
            set_accepted_terms_for_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
