# Initially generated by Django 5.0.6 on 2025-12-09 07:07

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from telegram_bots.models import TelegramBot
else:
    TelegramBot = Any


def disable_telegram_bots(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    telegram_bot_model: type[TelegramBot] = apps.get_model(
        'telegram_bots', 'TelegramBot'
    )
    telegram_bot_model.objects.update(must_be_enabled=False)


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]
    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(
                default=False, verbose_name='Принятие условий сервиса'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дата принятия условий сервиса'
            ),
        ),
        migrations.RunPython(
            disable_telegram_bots,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
