# Generated by Django 4.2.1 on 2023-07-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionsection',
            options={'ordering': ['position'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
