# Generated by Django 5.0.6 on 2025-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Позиция'),
        ),
    ]
