# Generated by Django 5.0 on 2024-01-12 19:02

import instruction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0005_alter_instructionsection_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsection',
            name='position',
            field=models.IntegerField(blank=True, default=instruction.models.instruction_section_position_default, verbose_name='Позиция'),
        ),
    ]
