# Generated by Django 5.0 on 2024-01-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0006_alter_instructionsection_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionsection',
            options={'ordering': ('position',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
