# Generated by Django 4.2.5 on 2023-10-08 21:24

from django.db import migrations, models
import donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Текст')),
                ('text_uk', models.CharField(max_length=255, null=True, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('position', models.IntegerField(blank=True, default=donation.models.DonationButton.position_default, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Кнопки',
                'db_table': 'donation_button',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['sum'], 'verbose_name': 'Пожертвование', 'verbose_name_plural': 'Пожертвования'},
        ),
        migrations.AlterField(
            model_name='donationsection',
            name='position',
            field=models.IntegerField(blank=True, default=donation.models.DonationSection.position_default, verbose_name='Позиция'),
        ),
    ]
