# Generated by Django 5.0.6 on 2025-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_convert_html_to_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
