# Generated by Django 5.0 on 2024-01-12 19:02

import donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbutton',
            name='position',
            field=models.IntegerField(blank=True, default=donation.models.donation_button_position_default, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='donationsection',
            name='position',
            field=models.IntegerField(blank=True, default=donation.models.donation_section_position_default, verbose_name='Позиция'),
        ),
    ]
