# Generated by Django 4.2.3 on 2023-07-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_alter_telegrambotuser_options_and_more'),
        ('plugin', '0002_rename_date_added_plugin_added_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='added_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='pluginlog',
            old_name='added_date',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='telegram_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='telegram_bot.telegrambot', verbose_name='Telegram бот'),
        ),
    ]
