# Generated by Django 4.2.3 on 2023-07-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_rename_added_date_plugin_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginlog',
            options={'verbose_name': 'Логи плагина', 'verbose_name_plural': 'Логи плагинов'},
        ),
    ]
