# Generated by Django 4.2.3 on 2023-09-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0004_alter_pluginlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginlog',
            options={'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.RenameField(
            model_name='plugin',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='pluginlog',
            old_name='date_added',
            new_name='added_date',
        ),
    ]
