# Generated by Django 4.2.3 on 2023-09-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_alter_pluginlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='pluginlog',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
    ]
