# Generated by Django 5.0.6 on 2024-07-23 14:25

from django.db import migrations, models
import secrets


def generate_token() -> str:
    return secrets.token_hex(25)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotsHub',
            fields=[
                ('url', models.URLField(unique=True, verbose_name='URL-адрес')),
                ('service_token', models.CharField(default=generate_token, max_length=50, primary_key=True, serialize=False, verbose_name='Токен сервиса')),
                ('microservice_token', models.CharField(max_length=50, verbose_name='Токен микросервиса')),
            ],
            options={
                'verbose_name': 'Центр',
                'verbose_name_plural': 'Центра',
                'db_table': 'telegram_bots_hub',
            },
        ),
    ]
