# Generated by Django 5.0.6 on 2025-08-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotshub',
            name='microservice_token',
            field=models.CharField(max_length=64, verbose_name='Токен микросервиса'),
        ),
        migrations.AlterField(
            model_name='telegrambotshub',
            name='service_token',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Токен сервиса'),
        ),
    ]
