# Generated by Django 4.1.6 on 2023-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('confirm_code', models.CharField(max_length=25, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('telegram_bots', models.ManyToManyField(related_name='telegram_bots', to='telegram_bot.telegrambot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
