# Generated by Django 4.2.1 on 2023-07-06 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_alter_telegrambotcommand_database_record'),
        ('user', '0007_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlagin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.TextField(verbose_name='Код')),
                ('is_checked', models.BooleanField(verbose_name='Проверен')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegrambot', verbose_name='Telegram бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Плагин пользователя',
                'verbose_name_plural': 'Плагины пользователей',
                'db_table': 'user_plagin',
            },
        ),
        migrations.CreateModel(
            name='UserPlaginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=7, verbose_name='Уровень')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('plagin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userplagin', verbose_name='Плагин')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegrambot', verbose_name='Telegram бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал плагина пользователя',
                'verbose_name_plural': 'Журналы плагинов пользователей',
                'db_table': 'user_plagin_log',
            },
        ),
    ]
