# Generated by Django 4.2.1 on 2023-07-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userplagin_userplaginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplaginlog',
            name='plagin',
        ),
        migrations.RemoveField(
            model_name='userplaginlog',
            name='telegram_bot',
        ),
        migrations.RemoveField(
            model_name='userplaginlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPlagin',
        ),
        migrations.DeleteModel(
            name='UserPlaginLog',
        ),
    ]
