# Generated by Django 4.2.3 on 2023-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_userpluginlog_plugin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя пользователя'),
        ),
    ]
