# Generated by Django 4.2.3 on 2023-07-11 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0014_alter_telegrambotuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.TextField(verbose_name='Код')),
                ('is_checked', models.BooleanField(verbose_name='Проверен')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegrambot', verbose_name='Telegram бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Плагин',
                'verbose_name_plural': 'Плагины',
                'db_table': 'plugin',
            },
        ),
        migrations.CreateModel(
            name='PluginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=7, verbose_name='Уровень')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugin.plugin', verbose_name='Плагин')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegrambot', verbose_name='Telegram бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал плагина',
                'verbose_name_plural': 'Журналы плагинов',
                'db_table': 'plugin_log',
            },
        ),
    ]
