# Generated by Django 4.2.3 on 2023-07-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='pluginlog',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='pluginlog',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plugin.plugin', verbose_name='Плагин'),
        ),
    ]
