# Generated by Django 4.2.3 on 2023-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_rename_added_date_plugin_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
