# Generated by Django 4.2.3 on 2023-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0006_alter_plugin_added_date_alter_pluginlog_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginlog',
            name='level',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('danger', 'Ошибка')], default='info', max_length=7, verbose_name='Уровень'),
        ),
    ]
