# Generated by Django 5.0.2 on 2024-02-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Изображение')),
                ('username', models.CharField(max_length=32, verbose_name='@username')),
                ('speciality', models.CharField(max_length=255, verbose_name='Специальность')),
                ('speciality_en', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('speciality_uk', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('speciality_ru', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('joined_date', models.DateTimeField(verbose_name='Присоединился')),
            ],
            options={
                'verbose_name': 'Члена',
                'verbose_name_plural': 'Члены',
                'ordering': ('joined_date',),
            },
        ),
    ]
