# Generated by Django 4.2.3 on 2023-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='joined_date',
            field=models.DateTimeField(verbose_name='Присоединился'),
        ),
    ]
