# Generated by Django 5.0 on 2024-01-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_teammember_options_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('joined_date',), 'verbose_name': 'Члена', 'verbose_name_plural': 'Члены'},
        ),
    ]
