# Generated by Django 4.2.1 on 2023-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/team/')),
                ('username', models.CharField(max_length=32, verbose_name='@username')),
                ('speciality', models.CharField(max_length=255, verbose_name='Специальность')),
                ('speciality_en', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('speciality_uk', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('speciality_ru', models.CharField(max_length=255, null=True, verbose_name='Специальность')),
                ('date_joined', models.DateTimeField(verbose_name='Дата присоединения')),
            ],
            options={
                'verbose_name': 'Члена команды',
                'verbose_name_plural': 'Члены команды',
                'db_table': 'team_members',
            },
        ),
    ]
