# Generated by Django 4.2.1 on 2023-06-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_member',
        ),
    ]
