# Generated by Django 4.2.5 on 2023-10-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['joined_date'], 'verbose_name': 'Члена', 'verbose_name_plural': 'Члены'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team/', verbose_name='Изображение'),
        ),
    ]
