# Generated by Django 4.2.3 on 2023-07-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_alter_instructionsection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionsection',
            options={'ordering': ['position'], 'verbose_name': 'Раздел инструкции', 'verbose_name_plural': 'Разделы инструкции'},
        ),
    ]
