from telegram_bot.services.constructor_telegram_bot.telegram_bot import TelegramBot as ConstructorTelegramBot
from telegram_bot.services.user_telegram_bot.telegram_bot import TelegramBot as UserTelegramBot
