# Generated by Django 4.2.1 on 2023-06-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
        migrations.AlterModelTable(
            name='update',
            table='update',
        ),
    ]
