# Generated by Django 4.2.1 on 2023-07-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelike',
            name='update',
        ),
        migrations.RemoveField(
            model_name='updatelike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='update',
            name='views',
        ),
        migrations.DeleteModel(
            name='UpdateComment',
        ),
        migrations.DeleteModel(
            name='UpdateLike',
        ),
    ]
