# Generated by Django 4.2.3 on 2023-07-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_remove_update_title_en_remove_update_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date_added'], 'verbose_name': 'Обновление', 'verbose_name_plural': 'Обновления'},
        ),
    ]
