# Generated by Django 4.2.3 on 2023-09-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-added_date'], 'verbose_name': 'Обновление', 'verbose_name_plural': 'Обновления'},
        ),
        migrations.RenameField(
            model_name='update',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='title',
            new_name='version',
        ),
    ]
