# Generated by Django 4.2.1 on 2023-06-01 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotCommandKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('default', 'Default'), ('inline', 'Inline')], default='default', max_length=7)),
            ],
            options={
                'db_table': 'telegram_bot_command_keyboard',
            },
        ),
        migrations.RenameField(
            model_name='telegrambot',
            old_name='date_added',
            new_name='_date_added',
        ),
        migrations.RenameField(
            model_name='telegrambotuser',
            old_name='date_activated',
            new_name='_date_activated',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='users',
        ),
        migrations.RemoveField(
            model_name='telegrambotcommand',
            name='callback',
        ),
        migrations.RemoveField(
            model_name='telegrambotcommand',
            name='keyboard',
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='diagram_current_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrambotcommand',
            name='api_request',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='telegrambotcommand',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='telegrambotcommand',
            name='telegram_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='telegram_bot.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrambotcommand',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegrambotcommand',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='telegram_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='telegram_bot.telegrambot'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='is_private',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='message_text',
            field=models.TextField(max_length=4096),
        ),
        migrations.CreateModel(
            name='TelegramBotCommandKeyboardButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('start_diagram_connector', models.TextField(null=True)),
                ('end_diagram_connector', models.TextField(null=True)),
                ('telegram_bot_command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.telegrambotcommand')),
                ('telegram_bot_command_keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='telegram_bot.telegrambotcommandkeyboard')),
            ],
            options={
                'db_table': 'telegram_bot_command_keyboard_button',
            },
        ),
        migrations.AddField(
            model_name='telegrambotcommandkeyboard',
            name='telegram_bot_command',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='telegram_bot.telegrambotcommand'),
        ),
    ]
