# Generated by Django 4.2.1 on 2023-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegrambotcommandkeyboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotuser',
            name='username',
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='full_name',
            field=models.CharField(max_length=129, null=True),
        ),
    ]
