# Generated by Django 4.2.1 on 2023-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegrambotcommandkeyboardbutton_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotcommandkeyboardbutton',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
