# Generated by Django 4.2.1 on 2023-06-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0005_telegrambotcommandkeyboardbutton_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Telegram бота', 'verbose_name_plural': 'Telegram боты'},
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='_date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='is_private',
            field=models.BooleanField(verbose_name='Приватный'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Запущен'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='@username'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
