# Generated by Django 4.2.1 on 2023-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_rename_name_telegrambot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Включён'),
        ),
    ]
