# Generated by Django 4.2.1 on 2023-07-02 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_rename__date_added_telegrambot_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotcommand',
            options={'verbose_name': 'Команда Telegram бота', 'verbose_name_plural': 'Команды Telegram ботов'},
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='api_request',
            field=models.JSONField(blank=True, null=True, verbose_name='API-запрос'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='command',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/commands/'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='message_text',
            field=models.TextField(max_length=4096, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='telegram_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='telegram_bot.telegrambot', verbose_name='Telegram бот'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='x',
            field=models.IntegerField(default=0, verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Координата Y'),
        ),
    ]
