# Generated by Django 4.2.1 on 2023-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_telegrambotcommand_database_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='database_record',
            field=models.TextField(blank=True, null=True, verbose_name='Запись в базу данных'),
        ),
    ]
