# Generated by Django 4.2.3 on 2023-08-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_alter_telegrambotuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotcommandkeyboardbutton',
            options={'ordering': ['id']},
        ),
    ]
