# Generated by Django 4.2.5 on 2023-10-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0020_alter_telegrambot_owner_alter_telegrambot_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcommandmessagetext',
            name='mode',
        ),
    ]
