# Generated by Django 4.2.5 on 2023-12-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_alter_telegrambotcommand_telegram_bot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotcommandapirequest',
            old_name='data',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='telegrambotcommandkeyboard',
            old_name='mode',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='telegrambotuser',
            old_name='user_id',
            new_name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='telegrambotcommand',
            name='database_record',
        ),
        migrations.RemoveField(
            model_name='telegrambotcommandcommand',
            name='is_show_in_menu',
        ),
    ]
