# Generated by Django 5.0 on 2024-01-05 09:15

import django.db.models.deletion
import telegram_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0024_remove_telegrambot_diagram_current_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcommand',
            name='image',
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='is_stopped',
            field=models.BooleanField(default=True, verbose_name='Выключен'),
        ),
        migrations.CreateModel(
            name='TelegramBotCommandDatabaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('telegram_bot_command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_record', to='telegram_bot.telegrambotcommand')),
            ],
            options={
                'db_table': 'telegram_bot_command_database_record',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotCommandFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=telegram_bot.models.upload_telegram_bot_command_file_path, verbose_name='Файл')),
                ('telegram_bot_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='telegram_bot.telegrambotcommand')),
            ],
            options={
                'db_table': 'telegram_bot_command_file',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotCommandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=telegram_bot.models.upload_telegram_bot_command_file_path, verbose_name='Изображение')),
                ('telegram_bot_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telegram_bot.telegrambotcommand')),
            ],
            options={
                'db_table': 'telegram_bot_command_image',
            },
        ),
    ]
