# Generated by Django 5.0 on 2024-01-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0025_remove_telegrambotcommand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotCommandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply_to_user_message', models.BooleanField(default=False, verbose_name='Ответить на сообщение пользователя')),
                ('is_delete_user_message', models.BooleanField(default=False, verbose_name='Удалить сообщение пользователя')),
                ('is_send_as_new_message', models.BooleanField(default=False, verbose_name='Отправить сообщение как новое')),
                ('telegram_bot_command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='telegram_bot.telegrambotcommand')),
            ],
            options={
                'db_table': 'telegram_bot_command_settings',
            },
        ),
    ]
