# Generated by Django 5.0 on 2024-01-09 17:53

import telegram_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0026_telegrambotcommandsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotcommandimage',
            name='image',
            field=models.ImageField(upload_to=telegram_bot.models.upload_telegram_bot_command_image_path, verbose_name='Изображение'),
        ),
    ]
