# Generated by Django 5.0 on 2024-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0027_alter_telegrambotcommandimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotuser',
            name='last_activity_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последней активности'),
        ),
    ]
