# Generated by Django 5.0 on 2024-01-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0028_telegrambotuser_last_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('value', models.TextField(max_length=2048, verbose_name='Значение')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='telegram_bot.telegrambot', verbose_name='Telegram бот')),
            ],
        ),
    ]
