# Generated by Django 5.0 on 2024-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0030_alter_telegrambot_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='x',
            field=models.FloatField(default=0, verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommand',
            name='y',
            field=models.FloatField(default=0, verbose_name='Координата Y'),
        ),
    ]
