# Generated by Django 5.0 on 2024-01-22 19:33

import telegram_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0031_alter_telegrambotcommand_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='api_token',
            field=models.CharField(max_length=50, unique=True, validators=[telegram_bot.models.validate_api_token], verbose_name='API-токен'),
        ),
    ]
