# Generated by Django 5.0 on 2024-02-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0032_alter_telegrambot_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='memory_limit',
            field=models.BigIntegerField(default=41943040, verbose_name='Лимит памяти'),
        ),
    ]
