# Generated by Django 5.0.2 on 2024-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0035_rename_is_running_telegrambot_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotuser',
            name='full_name',
            field=models.CharField(max_length=129, verbose_name='Имя и фамилия'),
        ),
    ]
