# Generated by Django 5.0.2 on 2024-02-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0036_alter_telegrambotuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='storage_size',
            field=models.PositiveBigIntegerField(default=41943040, verbose_name='Размер хранилища'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommandkeyboardbutton',
            name='row',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='telegrambotcommandkeyboardbutton',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='telegrambotuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(verbose_name='Telegram ID'),
        ),
    ]
