# Generated by Django 5.0.2 on 2024-02-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0037_alter_telegrambot_storage_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotvariable',
            options={'verbose_name': 'Переменная', 'verbose_name_plural': 'Переменные'},
        ),
        migrations.AlterModelTable(
            name='telegrambotvariable',
            table='telegram_bot_variable',
        ),
    ]
