# Generated by Django 4.2.1 on 2023-07-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_remove_updatelike_update_remove_updatelike_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='update',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='update',
            name='title_uk',
        ),
    ]
