# Generated by Django 4.2.3 on 2023-09-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_alter_update_added_date_alter_update_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(upload_to='updates/'),
        ),
    ]
