# Generated by Django 4.2.5 on 2023-10-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_alter_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(upload_to='updates/', verbose_name='Изображение'),
        ),
    ]
