# Generated by Django 5.0 on 2023-12-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_alter_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/', verbose_name='Изображение'),
        ),
    ]
