# Generated by Django 5.0.2 on 2024-02-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('x', models.FloatField(default=0, verbose_name='Координата X')),
                ('y', models.FloatField(default=0, verbose_name='Координата Y')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
                'db_table': 'telegram_bot_condition',
            },
        ),
        migrations.CreateModel(
            name='ConditionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('+', 'Положительный'), ('-', 'Отрицательный')], max_length=1, verbose_name='Тип')),
                ('first_value', models.CharField(max_length=255, verbose_name='Первое значение')),
                ('operator', models.CharField(choices=[('==', 'Равно'), ('!=', 'Не равно'), ('>', 'Больше'), ('>=', 'Больше или равно'), ('<', 'Меньше'), ('<=', 'Меньше или равно')], max_length=2, verbose_name='Оператор')),
                ('second_value', models.CharField(max_length=255, verbose_name='Второе значение')),
                ('next_part_operator', models.CharField(blank=True, choices=[('&&', 'И'), ('||', 'ИЛИ')], max_length=2, null=True, verbose_name='Оператор для следующей части')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='telegram_bots.condition', verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Часть условия',
                'verbose_name_plural': 'Части условий',
                'db_table': 'telegram_bot_condition_part',
            },
        ),
    ]
