# Generated by Django 5.0.2 on 2024-02-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0002_condition_conditionpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('x', models.FloatField(default=0, verbose_name='Координата X')),
                ('y', models.FloatField(default=0, verbose_name='Координата Y')),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, '1 день'), (3, '3 дня'), (7, '7 дней'), (14, '14 дней'), (28, '28 дней')], verbose_name='Интервал')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Фоновая задача',
                'verbose_name_plural': 'Фоновые задачи',
                'db_table': 'telegram_bot_background_task',
            },
        ),
        migrations.CreateModel(
            name='BackgroundTaskAPIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL-адрес')),
                ('method', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH'), ('delete', 'DELETE')], default='get', max_length=6, verbose_name='Метод')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Заголовки')),
                ('body', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('background_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_request', to='telegram_bots.backgroundtask', verbose_name='Фоновая задача')),
            ],
            options={
                'verbose_name': 'API-запрос',
                'verbose_name_plural': 'API-запросы',
                'db_table': 'telegram_bot_background_task_api_request',
            },
        ),
    ]
