# Generated by Django 5.0.6 on 2025-08-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0006_databaseoperation_databasecreateoperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandsettings',
            old_name='is_delete_user_message',
            new_name='delete_user_message',
        ),
        migrations.RenameField(
            model_name='commandsettings',
            old_name='is_reply_to_user_message',
            new_name='reply_to_user_message',
        ),
        migrations.RemoveField(
            model_name='commandsettings',
            name='is_send_as_new_message',
        ),
        migrations.AddField(
            model_name='commandsettings',
            name='send_as_new_message',
            field=models.BooleanField(default=True, verbose_name='Отправить сообщение как новое'),
        ),
    ]
