# Generated by Django 5.0.6 on 2025-08-28 08:42

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('telegram_bots', '0007_rename_is_delete_user_message_commandsettings_delete_user_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='connection',
            name='telegram_bo_source__bb2efb_idx',
        ),
        migrations.AddIndex(
            model_name='commandkeyboardbutton',
            index=models.Index(fields=['text'], name='telegram_bo_text_f748fe_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='telegram_bo_source__950e28_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='telegram_bo_target__b66ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='databaserecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='telegram_bo_data_92dfd0_gin'),
        ),
        migrations.AddIndex(
            model_name='triggercommand',
            index=models.Index(fields=['command'], name='telegram_bo_command_c9d0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='triggercommand',
            index=models.Index(fields=['payload'], name='telegram_bo_payload_ab2f44_idx'),
        ),
        migrations.AddIndex(
            model_name='triggercommand',
            index=models.Index(fields=['description'], name='telegram_bo_descrip_1c3d19_idx'),
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['name'], name='telegram_bo_name_7e7a7d_idx'),
        ),
    ]
