# Generated by Django 5.0.6 on 2025-09-03 21:26

import constructor_telegram_bots.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0008_remove_connection_telegram_bo_source__bb2efb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='body',
            field=constructor_telegram_bots.fields.StrictJSONField(blank=True, null=True, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='headers',
            field=constructor_telegram_bots.fields.StrictJSONField(allowed_types=(dict,), blank=True, null=True, verbose_name='Заголовки'),
        ),
        migrations.AlterField(
            model_name='databasecreateoperation',
            name='data',
            field=constructor_telegram_bots.fields.StrictJSONField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='databaserecord',
            name='data',
            field=constructor_telegram_bots.fields.StrictJSONField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='databaseupdateoperation',
            name='new_data',
            field=constructor_telegram_bots.fields.StrictJSONField(verbose_name='Новые данные'),
        ),
    ]
