# Generated by Django 5.0.6 on 2025-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0010_update_text_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggermessage',
            name='text',
            field=models.TextField(max_length=4096, null=True, verbose_name='Текст'),
        ),
    ]
