# Initially generated by Django 5.0.6 on 2025-12-03 21:41

from django.apps.registry import Apps
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import QuerySet
from django.db.models.fields.files import FieldFile
import django.db.models.deletion

import constructor_telegram_bots.fields
import telegram_bots.models.base

from contextlib import suppress
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..models import (
        Connection,
        Message,
        MessageDocument,
        MessageImage,
        MessageKeyboard,
        MessageKeyboardButton,
        MessageSettings,
        TelegramBot,
    )

    class CommandSettings(models.Model):
        reply_to_user_message: bool
        delete_user_message: bool
        send_as_new_message: bool

    class CommandMedia(models.Model):
        file: FieldFile
        from_url: str | None
        position: int

    class CommandImage(CommandMedia):
        pass

    class CommandDocument(CommandMedia):
        pass

    class CommandMessage(models.Model):
        text: str

    class CommandKeyboardButton(models.Model):
        id: int
        row: int
        position: int
        text: str
        url: str | None

    class CommandKeyboard(models.Model):
        type: str
        buttons: models.Manager[CommandKeyboardButton]

    class Command(models.Model):
        id: int
        telegram_bot: TelegramBot
        name: str
        settings: CommandSettings
        message: CommandMessage
        images: models.Manager[CommandImage]
        documents: models.Manager[CommandDocument]
        keyboard: CommandKeyboard
        x: int
        y: int
else:
    TelegramBot = Any
    Connection = Any

    Command = Any
    CommandSettings = Any
    CommandImage = Any
    CommandDocument = Any
    CommandMessage = Any
    CommandKeyboardButton = Any
    CommandKeyboard = Any

    Message = Any
    MessageSettings = Any
    MessageImage = Any
    MessageDocument = Any
    MessageKeyboardButton = Any
    MessageKeyboard = Any


def migrate_command_models(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    command_model: type[Command] = apps.get_model('telegram_bots', 'Command')
    command_keyboard_model: type[Command] = apps.get_model(
        'telegram_bots', 'CommandKeyboard'
    )
    command_keyboard_button_model: type[Command] = apps.get_model(
        'telegram_bots', 'CommandKeyboardButton'
    )

    message_model: type[Message] = apps.get_model('telegram_bots', 'Message')
    message_settings_model: type[MessageSettings] = apps.get_model(
        'telegram_bots', 'MessageSettings'
    )
    message_image_model: type[MessageImage] = apps.get_model(
        'telegram_bots', 'MessageImage'
    )
    message_document_model: type[MessageDocument] = apps.get_model(
        'telegram_bots', 'MessageDocument'
    )
    message_keyboard_model: type[MessageKeyboard] = apps.get_model(
        'telegram_bots', 'MessageKeyboard'
    )
    message_keyboard_button_model: type[MessageKeyboardButton] = apps.get_model(
        'telegram_bots', 'MessageKeyboardButton'
    )

    connection_model: type[Connection] = apps.get_model('telegram_bots', 'Connection')
    content_type_model: type[ContentType] = apps.get_model(
        'contenttypes', 'ContentType'
    )

    command_content_type: ContentType = content_type_model.objects.get_for_model(
        command_model
    )
    command_keyboard_button_content_type: ContentType = (
        content_type_model.objects.get_for_model(command_keyboard_button_model)
    )

    message_content_type: ContentType = content_type_model.objects.get_for_model(
        message_model
    )
    message_keyboard_button_content_type: ContentType = (
        content_type_model.objects.get_for_model(message_keyboard_button_model)
    )

    create_connections: list[Connection] = []

    command_id_map: dict[int, int] = {}
    command_keyboard_button_id_map: dict[int, int] = {}

    for command in command_model.objects.iterator():  # type: ignore [attr-defined]
        telegram_bot: TelegramBot = command.telegram_bot

        message: Message = message_model.objects.create(
            telegram_bot=telegram_bot,
            name=command.name,
            text=command.message.text,
            x=command.x,
            y=command.y,
        )
        command_id_map[command.id] = message.id

        message_settings_model.objects.create(
            message=message,
            reply_to_user_message=command.settings.reply_to_user_message,
            delete_user_message=command.settings.delete_user_message,
            send_as_new_message=command.settings.send_as_new_message,
        )
        message_image_model.objects.bulk_create(
            [
                message_image_model(
                    message=message,
                    file=command_image.file,
                    from_url=command_image.from_url,
                    position=command_image.position,
                )
                for command_image in command.images.all()
            ]
        )
        message_document_model.objects.bulk_create(
            [
                message_document_model(
                    message=message,
                    file=command_document.file,
                    from_url=command_document.from_url,
                    position=command_document.position,
                )
                for command_document in command.documents.all()
            ]
        )

        with suppress(command_keyboard_model.DoesNotExist):
            message_keyboard: MessageKeyboard = message_keyboard_model.objects.create(
                message=message, type=command.keyboard.type
            )

            for command_keyboard_button in command.keyboard.buttons.all():
                message_keyboard_button: MessageKeyboardButton = (
                    message_keyboard_button_model.objects.create(
                        keyboard=message_keyboard,
                        row=command_keyboard_button.row,
                        position=command_keyboard_button.position,
                        text=command_keyboard_button.text,
                        url=command_keyboard_button.url,
                    )
                )
                command_keyboard_button_id_map[command_keyboard_button.id] = (
                    message_keyboard_button.id
                )

        command_source_connections: QuerySet[Connection] = (
            connection_model.objects.filter(
                source_content_type=command_content_type, source_object_id=command.id
            ).exclude(target_content_type=command_content_type)
        )

        create_connections.extend(
            connection_model(
                telegram_bot=telegram_bot,
                source_content_type=message_content_type,
                source_object_id=message.id,
                source_handle_position=source_connection.source_handle_position,
                target_content_type=source_connection.target_content_type,
                target_object_id=source_connection.target_object_id,
                target_handle_position=source_connection.target_handle_position,
            )
            for source_connection in command_source_connections
        )
        command_source_connections.delete()

        command_target_connections: QuerySet[Connection] = (
            connection_model.objects.filter(
                target_content_type=command_content_type, target_object_id=command.id
            )
            .exclude(source_content_type=command_content_type)
            .exclude(source_content_type=command_keyboard_button_content_type)
        )

        create_connections.extend(
            connection_model(
                telegram_bot=telegram_bot,
                source_content_type=target_connection.source_content_type,
                source_object_id=target_connection.source_object_id,
                source_handle_position=target_connection.source_handle_position,
                target_content_type=message_content_type,
                target_object_id=message.id,
                target_handle_position=target_connection.target_handle_position,
            )
            for target_connection in command_target_connections
        )
        command_target_connections.delete()

    command_connections: QuerySet[Connection] = connection_model.objects.filter(
        source_content_type=command_content_type,
        target_content_type=command_content_type,
    )

    create_connections.extend(
        connection_model(
            telegram_bot=connection.telegram_bot,
            source_content_type=message_content_type,
            source_object_id=command_id_map[connection.source_object_id],
            source_handle_position=connection.source_handle_position,
            target_content_type=message_content_type,
            target_object_id=command_id_map[connection.target_object_id],
            target_handle_position=connection.target_handle_position,
        )
        for connection in command_connections
    )
    command_connections.delete()

    command_keyboard_button_source_connections = connection_model.objects.filter(
        source_content_type=command_keyboard_button_content_type
    )

    create_connections.extend(
        connection_model(
            telegram_bot=source_connection.telegram_bot,
            source_content_type=message_keyboard_button_content_type,
            source_object_id=command_keyboard_button_id_map[
                source_connection.source_object_id
            ],
            source_handle_position=source_connection.source_handle_position,
            target_content_type=(
                message_content_type
                if source_connection.target_content_type.id == command_content_type.id
                else source_connection.target_content_type
            ),
            target_object_id=(
                command_id_map[source_connection.target_object_id]
                if source_connection.target_content_type.id == command_content_type.id
                else source_connection.target_object_id
            ),
            target_handle_position=source_connection.target_handle_position,
        )
        for source_connection in command_keyboard_button_source_connections
    )
    command_keyboard_button_source_connections.delete()

    connection_model.objects.bulk_create(create_connections)


class Migration(migrations.Migration):
    dependencies = [('telegram_bots', '0011_alter_triggermessage_text')]
    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                (
                    'x',
                    models.FloatField(
                        default=telegram_bots.models.base.generate_random_coordinate,
                        verbose_name='Координата X',
                    ),
                ),
                (
                    'y',
                    models.FloatField(
                        default=telegram_bots.models.base.generate_random_coordinate,
                        verbose_name='Координата Y',
                    ),
                ),
                ('text', models.TextField(max_length=4096, verbose_name='Текст')),
                (
                    'telegram_bot',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='telegram_bots.telegrambot',
                        verbose_name='Telegram бот',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'telegram_bot_message',
            },
        ),
        migrations.CreateModel(
            name='MessageDocument',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'from_url',
                    constructor_telegram_bots.fields.PublicURLField(
                        blank=True, null=True, verbose_name='Из URL-адреса'
                    ),
                ),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=telegram_bots.models.base.upload_media_path,
                        verbose_name='Документ',
                    ),
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='telegram_bots.message',
                        verbose_name='Сообщение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Документ сообщения',
                'verbose_name_plural': 'Документы сообщений',
                'db_table': 'telegram_bot_message_document',
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'from_url',
                    constructor_telegram_bots.fields.PublicURLField(
                        blank=True, null=True, verbose_name='Из URL-адреса'
                    ),
                ),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                (
                    'file',
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=telegram_bots.models.base.upload_media_path,
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='telegram_bots.message',
                        verbose_name='Сообщение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение сообщения',
                'verbose_name_plural': 'Изображения сообщений',
                'db_table': 'telegram_bot_message_image',
            },
        ),
        migrations.CreateModel(
            name='MessageKeyboard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('default', 'Обычный'),
                            ('inline', 'Встроенный'),
                            ('payment', 'Платёжный'),
                        ],
                        default='default',
                        max_length=7,
                        verbose_name='Режим',
                    ),
                ),
                (
                    'message',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='keyboard',
                        to='telegram_bots.message',
                        verbose_name='Сообщение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Клавиатура сообщения',
                'verbose_name_plural': 'Клавиатуры сообщений',
                'db_table': 'telegram_bot_message_keyboard',
            },
        ),
        migrations.CreateModel(
            name='MessageKeyboardButton',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('text', models.TextField(max_length=512, verbose_name='Текст')),
                (
                    'url',
                    constructor_telegram_bots.fields.PublicURLField(
                        blank=True, null=True, verbose_name='URL-адрес'
                    ),
                ),
                (
                    'keyboard',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='buttons',
                        to='telegram_bots.messagekeyboard',
                        verbose_name='Клавиатура',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Кнопка клавиатуры сообщения',
                'verbose_name_plural': 'Кнопки клавиатур сообщений',
                'db_table': 'telegram_bot_message_keyboard_button',
            },
        ),
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'reply_to_user_message',
                    models.BooleanField(
                        default=False, verbose_name='Ответить на сообщение пользователя'
                    ),
                ),
                (
                    'delete_user_message',
                    models.BooleanField(
                        default=False, verbose_name='Удалить сообщение пользователя'
                    ),
                ),
                (
                    'send_as_new_message',
                    models.BooleanField(
                        default=True, verbose_name='Отправить сообщение как новое'
                    ),
                ),
                (
                    'message',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settings',
                        to='telegram_bots.message',
                        verbose_name='Сообщение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Настройки сообщения',
                'verbose_name_plural': 'Настройки сообщений',
                'db_table': 'telegram_bot_message_settings',
            },
        ),
        migrations.AddIndex(
            model_name='messagekeyboardbutton',
            index=models.Index(fields=['text'], name='telegram_bo_text_5f766c_idx'),
        ),
        migrations.RunPython(
            migrate_command_models, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name='command', name='telegram_bot'),
        migrations.RemoveField(model_name='commandmessage', name='command'),
        migrations.RemoveField(model_name='commandkeyboard', name='command'),
        migrations.RemoveField(model_name='commandsettings', name='command'),
        migrations.RemoveField(model_name='commanddocument', name='command'),
        migrations.RemoveField(model_name='commandkeyboardbutton', name='keyboard'),
        migrations.DeleteModel(name='CommandImage'),
        migrations.DeleteModel(name='CommandMessage'),
        migrations.DeleteModel(name='CommandSettings'),
        migrations.DeleteModel(name='Command'),
        migrations.DeleteModel(name='CommandDocument'),
        migrations.DeleteModel(name='CommandKeyboard'),
        migrations.DeleteModel(name='CommandKeyboardButton'),
    ]
