# Generated by Django 5.0.6 on 2025-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0012_rename_commands_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=None, max_length=4096, null=True, verbose_name='Текст'),
        ),
    ]
