# Generated by Django 5.0.6 on 2025-12-30 21:31

import constructor_telegram_bots.fields
import django.core.validators
import django.db.models.deletion
import telegram_bots.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0013_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('x', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата X')),
                ('y', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата Y')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'db_table': 'telegram_bot_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_url', constructor_telegram_bots.fields.PublicURLField(blank=True, null=True, verbose_name='Из URL-адреса')),
                ('file', models.ImageField(blank=True, max_length=500, null=True, upload_to=telegram_bots.models.base.upload_media_path, verbose_name='Изображение')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='telegram_bots.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Изображение счёта',
                'verbose_name_plural': 'Изображения счетов',
                'db_table': 'telegram_bot_invoice_image',
            },
        ),
        migrations.CreateModel(
            name='InvoicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Подпись')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='telegram_bots.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Цена счёта',
                'verbose_name_plural': 'Цены счетов',
                'db_table': 'telegram_bot_invoice_price',
            },
        ),
    ]
