# Generated by Django 5.0.6 on 2026-02-06 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0014_invoice_invoiceimage_invoiceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Разрешены только буквы, цифры, пробел и _.', regex='^[\\w ]+$')], verbose_name='Название'),
        ),
    ]
