# Generated by Django 5.2.11 on 2026-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0015_alter_variable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagekeyboardbutton',
            name='style',
            field=models.CharField(choices=[('default', 'По умолчанию'), ('primary', 'Основной'), ('success', 'Успех'), ('danger', 'Опасность')], default='default', max_length=7, verbose_name='Стиль'),
        ),
    ]
