# Generated by Django 5.2.11 on 2026-03-03 17:40

import django.core.validators
import django.db.models.deletion
import telegram_bots.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0016_messagekeyboardbutton_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата X')),
                ('y', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата Y')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Разрешены только буквы, цифры, пробел и _.', regex='^[\\w ]+$')], verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_variables', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Временная переменная',
                'verbose_name_plural': 'Временные переменные',
                'db_table': 'telegram_bot_temporary_variable',
            },
        ),
    ]
