# Initially generated by Django 5.2.12 on 2026-04-02 09:13

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..models import User as NewUser

    class User(NewUser):
        full_name: str
else:
    User = Any


def migrate_full_name(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    user_model: type[User] = apps.get_model('telegram_bots', 'User')

    update_users: list[User] = []

    for user in user_model.objects.iterator():
        full_name: str = user.full_name
        user.first_name = full_name[:64]
        user.last_name = full_name[65:]
        update_users.append(user)

    user_model.objects.bulk_update(update_users, fields=['first_name', 'last_name'])


class Migration(migrations.Migration):
    dependencies = [('telegram_bots', '0017_temporaryvariable')]
    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                default='UNKNOWN', max_length=64, verbose_name='Имя'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name='Фамилия'
            ),
        ),
        migrations.RunPython(migrate_full_name, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='user', name='full_name'),
    ]
