# Generated by Django 4.2.1 on 2023-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_bots',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
