# Generated by Django 4.2.3 on 2023-07-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userplugin_user_telegram_id_userpluginlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpluginlog',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='userpluginlog',
            name='telegram_bot',
        ),
        migrations.RemoveField(
            model_name='userpluginlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPlugin',
        ),
        migrations.DeleteModel(
            name='UserPluginLog',
        ),
    ]
