# Generated by Django 4.2.3 on 2023-09-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_username_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='joined_date',
        ),
    ]
