# Generated by Django 4.2.5 on 2023-10-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
