# Generated by Django 5.0 on 2024-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_last_name_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
