# Generated by Django 4.0.1 on 2022-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotCommandModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=256)),
                ('bot_id', models.BigIntegerField()),
                ('command', models.CharField(max_length=256)),
                ('command_answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Telegram Bot Command',
                'verbose_name_plural': 'Telegram Bot Commands',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotLogModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=256)),
                ('bot_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=256)),
                ('user_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Telegram Bot Log',
                'verbose_name_plural': 'Telegram Bot Logs',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
            },
        ),
    ]
