# Generated by Django 5.0 on 2024-01-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0002_privacypolicysection_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicysection',
            name='last_update_date',
        ),
    ]
