# Generated by Django 4.2.5 on 2023-10-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donationbutton_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-sum'], 'verbose_name': 'Пожертвование', 'verbose_name_plural': 'Пожертвования'},
        ),
    ]
